// SPDX-License-Identifier: Unlicense
#pragma once

#define VC_EXTRALEAN
#include <windows.h>
#include <devpropdef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void* HDRVSTORE;
typedef void* HDRIVERPACKAGE;

typedef enum _DRIVERSTORE_OBJECT_TYPE
{
	DriverDatabase = 0x00000001,
	DriverPackage = 0x00000002,
	DriverInfFile = 0x00000003,
	DriverFile = 0x00000004,
	DeviceId = 0x00000005,
	DeviceSetupClass = 0x00000006,
	DeviceNode = 0x00000007,
	DeviceInterfaceClass = 0x00000008,
	DeviceInterface = 0x00000009,
	DeviceContainer = 0x0000000A,
	DriverService = 0x0000000B,
	DriverRegKey = 0x0000000C,
	DevicePanel = 0x0000000D
} DRIVERSTORE_OBJECT_TYPE;

typedef enum _DRIVERSTORE_OPEN_FLAGS
{
	DRIVERSTORE_OPEN_NONE = 0x00000000,
	DRIVERSTORE_OPEN_CREATE = 0x00000001,
	DRIVERSTORE_OPEN_EXCLUSIVE = 0x00000002
} DRIVERSTORE_OPEN_FLAGS;

HDRVSTORE NWL_DriverStoreOpen(LPCSTR Drive, DWORD Flags);
BOOL NWL_DriverStoreClose(HDRVSTORE DriverStoreHandle);

#define DRVSTORE_LOCALE_NAME_MAX_LENGTH 85

typedef enum _DRIVERSTORE_ENUM_FLAGS
{
	DRIVERSTORE_ENUM_NONE = 0x00000000,
	DRIVERSTORE_ENUM_INBOX_ONLY = 0x00000001,
	DRIVERSTORE_ENUM_OEM_ONLY = 0x00000002,
	DRIVERSTORE_ENUM_PUBLISHED_ONLY = 0x00000004,
	DRIVERSTORE_ENUM_VALID = DRIVERSTORE_ENUM_INBOX_ONLY | DRIVERSTORE_ENUM_OEM_ONLY | DRIVERSTORE_ENUM_PUBLISHED_ONLY
} DRIVERSTORE_ENUM_FLAGS;

typedef enum _DRIVER_PACKAGE_FLAGS
{
	DRIVER_PACKAGE_NONE = 0x00000000,
	DRIVER_PACKAGE_INBOX = 0x00000001,
	DRIVER_PACKAGE_OEM = 0x00000002,
	DRIVER_PACKAGE_PUBLISHED = 0x00000004,
	DRIVER_PACKAGE_F6 = 0x00000008,
	DRIVER_PACKAGE_BASEVERSION = 0x00000010
} DRIVER_PACKAGE_FLAGS;

typedef struct _DRIVER_PACKAGE_INFO
{
	USHORT ProcessorArchitecture;
	WCHAR  LocaleName[DRVSTORE_LOCALE_NAME_MAX_LENGTH];
	WCHAR  PublishedInfName[MAX_PATH];
	DWORD  Flags;
} DRIVER_PACKAGE_INFO, * PDRIVER_PACKAGE_INFO;

typedef BOOL(CALLBACK* PDRIVERSTORE_ENUM_PACKAGE_CALLBACK)(HDRVSTORE DriverStoreHandle,
	LPCWSTR DriverStoreFilename, PDRIVER_PACKAGE_INFO DriverPackageInfo, LPARAM Context);

BOOL NWL_DriverStoreEnum(HDRVSTORE DriverStoreHandle, DWORD Flags, PDRIVERSTORE_ENUM_PACKAGE_CALLBACK CallbackRoutine, LPARAM Context);

typedef enum _DRIVERSTORE_IMPORT_FLAGS
{
	DRIVERSTORE_IMPORT_NONE = 0x00000000,
	DRIVERSTORE_IMPORT_SKIP_TEMP_COPY = 0x00000001,
	DRIVERSTORE_IMPORT_SKIP_EXTERNAL_FILE_CHECK = 0x00000002,
	DRIVERSTORE_IMPORT_NO_RESTORE_POINT = 0x00000004,
	DRIVERSTORE_IMPORT_NON_INTERACTIVE = 0x00000008,
	DRIVERSTORE_IMPORT_REPLACE = 0x00000020,
	DRIVERSTORE_IMPORT_HARDLINK = 0x00000040,
	DRIVERSTORE_IMPORT_PUBLISH_SAME_NAME = 0x00000100,
	DRIVERSTORE_IMPORT_INBOX = 0x00000200,
	DRIVERSTORE_IMPORT_F6 = 0x00000400,
	DRIVERSTORE_IMPORT_BASE_VERSION = 0x00000800,
	DRIVERSTORE_IMPORT_SYSTEM_DEFAULT_LOCALE = 0x00001000,
	DRIVERSTORE_IMPORT_SYSTEM_CRITICAL = 0x00002000
} DRIVERSTORE_IMPORT_FLAGS;

DWORD NWL_DriverStoreImport(HDRVSTORE DriverStoreHandle, LPCWSTR DriverPackageFileName,
	USHORT ProcessorArchitecture, LPCWSTR LocaleName, DWORD Flags, LPWSTR DriverStoreFileName, DWORD DriverStoreFileNameSize);

typedef enum _DRIVERSTORE_OFFLINE_ADD_DRIVER_PACKAGE_FLAGS
{
	DRIVERSTORE_OFFLINE_ADD_NONE = 0x00000000,
	DRIVERSTORE_OFFLINE_ADD_SKIP_INSTALL = 0x00000001,
	DRIVERSTORE_OFFLINE_ADD_INBOX = 0x00000002,
	DRIVERSTORE_OFFLINE_ADD_F6 = 0x00000004,
	DRIVERSTORE_OFFLINE_ADD_SKIP_EXTERNAL_FILE_PRESENCE_CHECK = 0x00000008,
	DRIVERSTORE_OFFLINE_ADD_NO_TEMP_COPY = 0x00000010,
	DRIVERSTORE_OFFLINE_ADD_USE_HARD_LINKS = 0x00000020,
	DRIVERSTORE_OFFLINE_ADD_INSTALL_ONLY = 0x00000040,
	DRIVERSTORE_OFFLINE_ADD_REPLACE_PACKAGE = 0x00000080,
	DRIVERSTORE_OFFLINE_ADD_FORCE = 0x00000100,
	DRIVERSTORE_OFFLINE_ADD_BASE_VERSION = 0x00000200
} DRIVERSTORE_OFFLINE_ADD_DRIVER_PACKAGE_FLAGS;

DWORD NWL_DriverStoreOfflineAddDriverPackage(LPCWSTR DriverPackageInfPath, DWORD Flags, HANDLE Reserved,
	USHORT ProcessorArchitecture, LPCWSTR LocaleName, LPWSTR DestInfPath, PDWORD CchDestInfPath,
	LPCWSTR TargetSystemRoot, LPCWSTR TargetSystemDrive);

typedef enum _DRIVERSTORE_PUBLISH_FLAGS
{
	DRIVERSTORE_PUBLISH_NONE = 0x00000000
} DRIVERSTORE_PUBLISH_FLAGS;

typedef enum _DRIVERSTORE_CONFIGURE_FLAGS
{
	DRIVERSTORE_CONFIGURE_NONE = 0x00000000,
	DRIVERSTORE_CONFIGURE_FORCE = 0x00000001,
	DRIVERSTORE_CONFIGURE_ACTIVE_ONLY = 0x00000002,
	DRIVERSTORE_CONFIGURE_SOURCE_CONFIGURATIONS = 0x00010000,
	DRIVERSTORE_CONFIGURE_SOURCE_DEVICE_IDS = 0x00020000,
	DRIVERSTORE_CONFIGURE_TARGET_DEVICE_NODES = 0x00100000
} DRIVERSTORE_CONFIGURE_FLAGS;

typedef enum _DRIVERSTORE_REFLECT_FLAGS
{
	DRIVERSTORE_REFLECT_NONE = 0x00000000,
	DRIVERSTORE_REFLECT_FILES_ONLY = 0x00000001,
	DRIVERSTORE_REFLECT_ACTIVE_DRIVERS = 0x00000002,
	DRIVERSTORE_REFLECT_EXTERNAL_ONLY = 0x00000004,
	DRIVERSTORE_REFLECT_CONFIGURATIONS = 0x00000008
} DRIVERSTORE_REFLECT_FLAGS;

typedef enum _DRIVERSTORE_REFLECT_CRITICAL_FLAGS
{
	DRIVERSTORE_REFLECT_CRITICAL_NONE = 0x00000000,
	DRIVERSTORE_REFLECT_CRITICAL_FORCE = 0x00000001,
	DRIVERSTORE_REFLECT_CRITICAL_CONFIGURATIONS = 0x00000002
} DRIVERSTORE_REFLECT_CRITICAL_FLAGS;

DWORD NWL_DriverStoreUpdateDevices(HDRVSTORE DriverStoreHandle, LPCWSTR DriverStoreFilename,
	DWORD Flags, LPCWSTR SourceFilter, LPCWSTR TargetFilter);
DWORD NWL_DriverStoreDelete(HDRVSTORE DriverStoreHandle, LPCWSTR DriverStoreFilename, DWORD Flags);
DWORD NWL_DriverStoreConfigure(HDRVSTORE DriverStoreHandle, LPCWSTR DriverStoreFilename,
	DWORD Flags, LPCWSTR SourceFilter, LPCWSTR TargetFilter);
DWORD NWL_DriverStoreReflectCritical(HDRVSTORE DriverStoreHandle, LPCWSTR DriverStoreFilename, DWORD Flags, LPCWSTR FilterDeviceId);
DWORD NWL_DriverStoreReflect(HDRVSTORE DriverStoreHandle, LPCWSTR DriverStoreFilename, DWORD Flags, LPCWSTR FilterSectionNames);
DWORD NWL_DriverStorePublish(HDRVSTORE DriverStoreHandle, LPCWSTR DriverStoreFilename,
	DWORD Flags, LPWSTR PublishedFileName, DWORD PublishedFileNameSize, PBOOL IsPublishedFileNameChanged);

typedef enum _DRIVERSTORE_LOCK_LEVEL
{
	DRIVERSTORE_LOCK_NONE = 0,
	DRIVERSTORE_LOCK_BASIC_PROTECTED = 1,
	DRIVERSTORE_LOCK_RUNTIME_ISOLATED = 2,
	DRIVERSTORE_LOCK_SYSTEM_PROTECTED = 3,
	DRIVERSTORE_LOCK_MAX = 4
} DRIVERSTORE_LOCK_LEVEL;

typedef BOOL(CALLBACK* PDRIVERSTORE_ENUM_OBJECTS_CALLBACK)(HDRVSTORE DriverStoreHandle,
	DWORD ObjectType, LPCWSTR ObjectName, LPARAM Context);

BOOL NWL_DriverStoreEnumObjects(HDRVSTORE DriverStoreHandle, DWORD ObjectType, DWORD Flags,
	PDRIVERSTORE_ENUM_OBJECTS_CALLBACK CallbackRoutine, LPARAM Context);

typedef enum _DRIVERSTORE_SET_OBJECT_PROPERTY_FLAGS
{
	DRIVERSTORE_SET_OBJECT_PROPERTY_NONE = 0x00000000
} DRIVERSTORE_SET_OBJECT_PROPERTY_FLAGS;

BOOL NWL_DriverStoreSetObjectProperty(HDRVSTORE DriverStoreHandle, DWORD ObjectType, LPCWSTR ObjectName,
	CONST DEVPROPKEY* PropertyKey, DEVPROPTYPE PropertyType, LPCVOID PropertyBuffer, DWORD PropertySize, DWORD Flags);
BOOL NWL_DriverStoreGetObjectProperty(HDRVSTORE DriverStoreHandle, DWORD ObjectType, LPCWSTR ObjectName,
	CONST DEVPROPKEY* PropertyKey, DEVPROPTYPE* PropertyType, PBYTE PropertyBuffer, DWORD BufferSize,
	PDWORD PropertySize, DWORD Flags);

typedef enum _DRIVER_PACKAGE_ENUM_FILES_FLAGS
{
	DRIVER_PACKAGE_ENUM_FILES_NONE = 0x00000000,
	DRIVER_PACKAGE_ENUM_FILES_COPY = 0x00000001,
	DRIVER_PACKAGE_ENUM_FILES_DELETE = 0x00000002,
	DRIVER_PACKAGE_ENUM_FILES_RENAME = 0x00000004,
	DRIVER_PACKAGE_ENUM_FILES_INF = 0x00000010,
	DRIVER_PACKAGE_ENUM_FILES_CATALOG = 0x00000020,
	DRIVER_PACKAGE_ENUM_FILES_BINARIES = 0x00000040,
	DRIVER_PACKAGE_ENUM_FILES_COPY_INFS = 0x00000080,
	DRIVER_PACKAGE_ENUM_FILES_INCLUDE_INFS = 0x00000100,
	DRIVER_PACKAGE_ENUM_FILES_EXTERNAL = 0x00001000,
	DRIVER_PACKAGE_ENUM_FILES_UNIQUE_SOURCE = 0x00002000,
	DRIVER_PACKAGE_ENUM_FILES_UNIQUE_DESTINATION = 0x00004000
} DRIVER_PACKAGE_ENUM_FILES_FLAGS;

typedef enum _DRIVER_PACKAGE_OPEN_FLAGS
{
	DRIVER_PACKAGE_OPEN_NONE = 0x00000000,
	DRIVER_PACKAGE_OPEN_VERSION_ONLY = 0x00000001,
	DRIVER_PACKAGE_OPEN_FILES_ONLY = 0x00000002,
	DRIVER_PACKAGE_OPEN_DEFAULT_LANGUAGE = 0x00000004,
	DRIVER_PACKAGE_OPEN_LOCALIZABLE_STRINGS = 0x00000008,
	DRIVER_PACKAGE_OPEN_TARGET_OS_VERSION = 0x00000010,
	DRIVER_PACKAGE_OPEN_STRICT_VALIDATION = 0x00000020,
	DRIVER_PACKAGE_OPEN_CLASS_SCHEMA_ONLY = 0x00000040,
	DRIVER_PACKAGE_OPEN_LOG_TELEMETRY = 0x00000080,
	DRIVER_PACKAGE_OPEN_PRIMARY_ONLY = 0x00000100
} DRIVER_PACKAGE_OPEN_FLAGS;

typedef enum _DRIVERSTORE_COPY_FLAGS
{
	DRIVERSTORE_COPY_NONE = 0x00000000,
	DRIVERSTORE_COPY_EXTERNAL = 0x00000001,
	DRIVERSTORE_COPY_COPY_INFS = 0x00000002,
	DRIVERSTORE_COPY_SKIP_EXISTING_COPY_INFS = 0x00000004,
	DRIVERSTORE_COPY_SYSTEM_DEFAULT_LOCALE = 0x00000008,
	DRIVERSTORE_COPY_HARDLINK = 0x00000010
} DRIVERSTORE_COPY_FLAGS;

typedef enum _DRIVER_FILE_OPERATION
{
	DRIVER_FILE_OPERATION_COPY = 0,
	DRIVER_FILE_OPERATION_DELETE = 1,
	DRIVER_FILE_OPERATION_RENAME = 2
} DRIVER_FILE_OPERATION;

typedef enum _DRIVER_FILE_TYPE
{
	DRIVER_FILE_TYPE_INF = 0,
	DRIVER_FILE_TYPE_CATALOG = 1,
	DRIVER_FILE_TYPE_BINARY = 2,
	DRIVER_FILE_TYPE_COPY_INF = 3,
	DRIVER_FILE_TYPE_INCLUDE_INF = 4
} DRIVER_FILE_TYPE;

typedef struct _DRIVER_FILE
{
	DWORD Operation;
	LPCWSTR ExternalFile;
	DWORD Type;
	DWORD Flags;
	LPCWSTR SourceFile;
	LPCWSTR SourcePath;
	LPCWSTR DestinationFile;
	LPCWSTR DestinationPath;
	LPCWSTR ArchiveFile;
	LPCWSTR SecurityDescriptor;
	LPCWSTR SectionName;
} DRIVER_FILE, * PDRIVER_FILE;

typedef enum _DRIVER_PACKAGE_GET_PROPERTY_FLAGS
{
	DRIVER_PACKAGE_GET_PROPERTY_NONE = 0x00000000
} DRIVER_PACKAGE_GET_PROPERTY_FLAGS;

typedef enum _DRIVER_PACKAGE_VERSION_INFO_FLAGS
{
	DRIVER_PACKAGE_VERSION_INFO_NONE = 0x00000000,
	DRIVER_PACKAGE_VERSION_INFO_HAS_DEVICE_DRIVERS = 0x00000001,
	DRIVER_PACKAGE_VERSION_INFO_PNP_LOCKDOWN = 0x00000002,
	DRIVER_PACKAGE_VERSION_INFO_FORCE_BOOT_CRITICAL = 0x00000004,
	DRIVER_PACKAGE_VERSION_INFO_FORCE_NOT_BOOT_CRITICAL = 0x00000008,
	DRIVER_PACKAGE_VERSION_INFO_HAS_DEVICE_CLASSES = 0x00000010,
	DRIVER_PACKAGE_VERSION_INFO_PRE_CONFIGURABLE = 0x00000020,
	DRIVER_PACKAGE_VERSION_INFO_HAS_DEVICES = 0x00000040,
	DRIVER_PACKAGE_VERSION_INFO_HAS_INTERFACE_CLASSES = 0x00000080,
	DRIVER_PACKAGE_VERSION_INFO_HAS_PRIMITIVE_DRIVERS = 0x00000100,
	DRIVER_PACKAGE_VERSION_INFO_HAS_DRIVERS =
	DRIVER_PACKAGE_VERSION_INFO_HAS_DEVICE_DRIVERS | DRIVER_PACKAGE_VERSION_INFO_HAS_PRIMITIVE_DRIVERS,
	DRIVER_PACKAGE_VERSION_INFO_HAS_CLASSES =
	DRIVER_PACKAGE_VERSION_INFO_HAS_DEVICE_CLASSES | DRIVER_PACKAGE_VERSION_INFO_HAS_INTERFACE_CLASSES
} DRIVER_PACKAGE_VERSION_INFO_FLAGS;

typedef struct _DRIVER_PACKAGE_VERSION_INFO
{
	DWORD Size;
	USHORT Architecture;
	WCHAR LocaleName[DRVSTORE_LOCALE_NAME_MAX_LENGTH];
	WCHAR ProviderName[MAX_PATH];
	FILETIME DriverDate;
	ULONGLONG DriverVersion;
	GUID ClassGuid;
	WCHAR ClassName[MAX_PATH];
	DWORD ClassVersion;
	WCHAR CatalogFile[MAX_PATH];
	DWORD Flags;
} DRIVER_PACKAGE_VERSION_INFO, * PDRIVER_PACKAGE_VERSION_INFO;

typedef enum _DRIVERSTORE_UPDATE_DEVICES_FLAGS
{
	DRIVERSTORE_UPDATE_DEVICES_FORCE = 0x00000001,
	DRIVERSTORE_UPDATE_DEVICES_NULL_DRIVER = 0x00000002,
	DRIVERSTORE_UPDATE_DEVICES_ALTERNATIVE_DRIVER = 0x00000004,
	DRIVERSTORE_UPDATE_DEVICES_SOURCE_CONFIGURATIONS = 0x00010000,
	DRIVERSTORE_UPDATE_DEVICES_SOURCE_DEVICE_IDS = 0x00020000,
	DRIVERSTORE_UPDATE_DEVICES_SOURCE_DRIVER_NAMES = 0x00040000,
	DRIVERSTORE_UPDATE_DEVICES_TARGET_INSTANCE_IDS = 0x00100000,
	DRIVERSTORE_UPDATE_DEVICES_TARGET_DEVICE_IDS = 0x00200000,
	DRIVERSTORE_UPDATE_DEVICES_VALID =
	DRIVERSTORE_UPDATE_DEVICES_FORCE | DRIVERSTORE_UPDATE_DEVICES_NULL_DRIVER |
	DRIVERSTORE_UPDATE_DEVICES_ALTERNATIVE_DRIVER | DRIVERSTORE_UPDATE_DEVICES_SOURCE_CONFIGURATIONS |
	DRIVERSTORE_UPDATE_DEVICES_SOURCE_DEVICE_IDS | DRIVERSTORE_UPDATE_DEVICES_SOURCE_DRIVER_NAMES |
	DRIVERSTORE_UPDATE_DEVICES_TARGET_INSTANCE_IDS | DRIVERSTORE_UPDATE_DEVICES_TARGET_DEVICE_IDS
} DRIVERSTORE_UPDATE_DEVICES_FLAGS;

typedef enum _DRIVERSTORE_DELETE_FLAGS
{
	DRIVERSTORE_DELETE_INBOX = 0x00000001,
	DRIVERSTORE_DELETE_UNCONFIGURE = 0x00000002,
	DRIVERSTORE_DELETE_UNCONFIGURE_ONLY = 0x00000004,
	DRIVERSTORE_DELETE_UNCONFIGURE_PRESERVE_STATE = 0x00010000,
	DRIVERSTORE_DELETE_UNCONFIGURE_VALID = DRIVERSTORE_DELETE_UNCONFIGURE_PRESERVE_STATE,
	DRIVERSTORE_DELETE_VALID =
	DRIVERSTORE_DELETE_INBOX | DRIVERSTORE_DELETE_UNCONFIGURE |
	DRIVERSTORE_DELETE_UNCONFIGURE_ONLY | DRIVERSTORE_DELETE_UNCONFIGURE_VALID
} DRIVERSTORE_DELETE_FLAGS;

typedef BOOL(CALLBACK* PDRIVER_PACKAGE_ENUM_FILES_CALLBACK)(HDRIVERPACKAGE DriverPackageHandle,
	PDRIVER_FILE DriverFile, LPARAM Context);

HDRIVERPACKAGE NWL_DriverPackageOpen(LPCWSTR DriverPackageFilename, USHORT ProcessorArchitecture,
	LPCWSTR LocaleName, DWORD Flags, HANDLE ResolveContext);
BOOL NWL_DriverPackageEnumFiles(HDRIVERPACKAGE DriverPackageHandle, PVOID EnumContext,
	DWORD Flags, PDRIVER_PACKAGE_ENUM_FILES_CALLBACK CallbackRoutine, LPARAM Context);
BOOL NWL_DriverPackageGetVersionInfo(HDRIVERPACKAGE DriverPackageHandle, PDRIVER_PACKAGE_VERSION_INFO VersionInfo);
BOOL NWL_DriverPackageGetProperty(HDRIVERPACKAGE DriverPackageHandle, PVOID EnumContext,
	LPCWSTR SectionName, CONST DEVPROPKEY* PropertyKey, DEVPROPTYPE* PropertyType, PVOID PropertyBuffer,
	DWORD BufferSize, PDWORD PropertySize, DWORD Flags);
VOID NWL_DriverPackageClose(HDRIVERPACKAGE DriverPackageHandle);
DWORD NWL_DriverStoreCopy(HDRVSTORE DriverStoreHandle, LPCWSTR DriverPackageFilename,
	USHORT ProcessorArchitecture, LPCWSTR LocaleName, DWORD Flags, LPCWSTR DestinationPath);

#ifdef __cplusplus
}
#endif
