// SPDX-License-Identifier: MPL-2.0

#pragma once

#define QUOTE_(x) #x
#define QUOTE(x) QUOTE_(x)

#define LIBLHM_MAJOR_VERSION 0
#define LIBLHM_MINOR_VERSION 0
#define LIBLHM_MICRO_VERSION 1
#define LIBLHM_BUILD_VERSION 0

#define LIBLHM_VERSION      LIBLHM_MAJOR_VERSION,LIBLHM_MINOR_VERSION,LIBLHM_MICRO_VERSION,LIBLHM_BUILD_VERSION
#define LIBLHM_VERSION_STR  QUOTE(LIBLHM_MAJOR_VERSION.LIBLHM_MINOR_VERSION.LIBLHM_MICRO_VERSION.LIBLHM_BUILD_VERSION)

#define LIBLHM_COMPANY      "A1ive"
#define LIBLHM_COPYRIGHT    "(C) 2026 A1ive"
#define LIBLHM_FILEDESC     "LHM CPP Wrapper"

#define LIBLHM_DLL          "liblhm"

