#pragma once

#define VC_EXTRALEAN
#include <windows.h>

typedef struct
{
	BYTE id;
	LPCWSTR name;
} SMART_NAME;

static SMART_NAME SMART_NAME_Smart[] =
{
	{0x01, L"Read Error Rate"},
	{0x02, L"Throughput Performance"},
	{0x03, L"Spin-Up Time"},
	{0x04, L"Start/Stop Count"},
	{0x05, L"Reallocated Sectors Count"},
	{0x06, L"Read Channel Margin"},
	{0x07, L"Seek Error Rate"},
	{0x08, L"Seek Time Performance"},
	{0x09, L"Power-On Hours"},
	{0x0A, L"Spin Retry Count"},
	{0x0B, L"Recalibration Retries"},
	{0x0C, L"Power Cycle Count"},
	{0x0D, L"Soft Read Error Rate stab"},
	{0x16, L"Current Helium Level"},
	{0xB8, L"End-to-End Error"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xBC, L"Command Timeout"},
	{0xBD, L"High Fly Writes"},
	{0xBE, L"Airflow Temperature"},
	{0xBF, L"G-Sense Error Rate"},
	{0xC0, L"Power-off Retract Count"},
	{0xC1, L"Load/Unload Cycle Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"Hardware ECC recovered"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Current Pending Sector Count"},
	{0xC6, L"Uncorrectable Sector Count"},
	{0xC7, L"UltraDMA CRC Error Count"},
	{0xC8, L"Write Error Rate"},
	{0xC9, L"Soft Read Error Rate"},
	{0xCA, L"Data Address Mark Error"},
	{0xCB, L"Run Out Cancel"},
	{0xCC, L"Soft ECC Correction"},
	{0xCD, L"Thermal Asperity Rate"},
	{0xCE, L"Flying Height"},
	{0xCF, L"Spin High Current"},
	{0xD0, L"Spin Buzz"},
	{0xD1, L"Offline Seek Performance"},
	{0xD3, L"Vibration During Write"},
	{0xD4, L"Shock During Write"},
	{0xDC, L"Disk Shift"},
	{0xDD, L"G-Sense Error Rate"},
	{0xDE, L"Loaded Hours"},
	{0xDF, L"Load/Unload Retry Count"},
	{0xE0, L"Load Friction"},
	{0xE1, L"Load/Unload Cycle Count"},
	{0xE2, L"Load 'In'-time"},
	{0xE3, L"Torque Amplification Count"},
	{0xE4, L"Power-Off Retract Cycle"},
	{0xE6, L"GMR Head Amplitude"},
	{0xE7, L"Temperature"},
	{0xF0, L"Head Flying Hours"},
	{0xFA, L"Read Error Retry Rate"},
	{0xFE, L"Free Fall Protection"},


	{0xF1, L"Total Host Writes"},
	{0xF2, L"Total Host Reads"},
};

static SMART_NAME SMART_NAME_SmartSsd[] =
{
	{0x01, L"Read Error Rate"},
	{0x02, L"Throughput Performance"},
	{0x03, L"Spin-Up Time"},
	{0x04, L"Start/Stop Count"},
	{0x05, L"Reallocated Sectors Count"},
	{0x06, L"Read Channel Margin"},
	{0x07, L"Seek Error Rate"},
	{0x08, L"Seek Time Performance"},
	{0x09, L"Power-On Hours"},
	{0x0A, L"Spin Retry Count"},
	{0x0B, L"Recalibration Retries"},
	{0x0C, L"Power Cycle Count"},
	{0x0D, L"Soft Read Error Rate stab"},
	{0xC0, L"Unsafe Shutdown Count"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Current Pending Sector Count"},
	{0xC6, L"Uncorrectable Sector Count"},
	{0xFF, L"Remaining Life"},
	{0xF1, L"Total Host Writes"},
	{0xF2, L"Total Host Reads"},
};

static SMART_NAME SMART_NAME_SmartMtron[] =
{
	{0xBB, L"Total Erase Count"},
};

static SMART_NAME SMART_NAME_SmartIndilinx[] =
{
	{0x01, L"Read Error Rate"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xB8, L"Initial Bad Block Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"Program Failure Block Count"},
	{0xC4, L"Erase Failure Block Count"},
	{0xC5, L"Read Failure Block Count"},
	{0xC6, L"Total Count of Read Sectors"},
	{0xC7, L"Total Count of Write Sectors"},
	{0xC8, L"Total Count of Read Commands"},
	{0xC9, L"Total Count of Write Commands"},
	{0xCA, L"Total Count of Error bits from flash"},
	{0xCB, L"Total Count of Read Sectors with Correctable Bit Errors"},
	{0xCC, L"Bad Block Full Flag"},
	{0xCD, L"Maximum PE Count Specification"},
	{0xCE, L"Minimum Erase Count"},
	{0xCF, L"Maximum Erase Count"},
	{0xD0, L"Average Erase Count"},
	{0xD1, L"Remaining Drive Life"},
};

static SMART_NAME SMART_NAME_SmartJMicron60x[] =
{
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xC2, L"Temperature"},
	{0xE5, L"Halt System ID, Flash ID"},
	{0xE8, L"Firmware Version Information"},
	{0xE9, L"ECC Fail Record"},
	{0xEA, L"Average Erase Count, Max Erase Count"},
	{0xEB, L"Good Block Count, System Block Count"},
};

static SMART_NAME SMART_NAME_SmartIntel[] =
{
	{0x03, L"Spin Up Time"},
	{0x04, L"Start/Stop Count"},
	{0x05, L"Re-Allocated Sector Count"},
	{0x09, L"Power-On Hours Count"},
	{0x0C, L"Power Cycle Count"},
	{0xAA, L"Available Reserved Space"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAE, L"Unexpected Power Loss"},
	{0xAF, L"Power Loss Protection Failure"},
	{0xB7, L"SATA Downshift Count"},
	{0xB8, L"End to End Error Detection Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBE, L"Temperature"},
	{0xC0, L"Unsafe Shutdown Count"},
	{0xC2, L"Temperature"},
	{0xC5, L"Pending Sector Count"},
	{0xC7, L"CRC Error Count"},
	{0xE1, L"Host Writes"},
	{0xE2, L"Timed Workload Media Wear"},
	{0xE3, L"Timed Workload Host Read/Write Ratio"},
	{0xE4, L"Timed Workload Timer"},
	{0xE8, L"Available Reserved Space"},
	{0xE9, L"Media Wearout Indicator"},
	{0xEA, L"Thermal Throttle Status"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
	{0xF3, L"Total NAND Writes"},
	{0xF9, L"Total NAND Writes"},
};

static SMART_NAME SMART_NAME_SmartSamsung[] =
{
	{0x05, L"Reallocated Sector Count"},
	{0x09, L"Power-on Hours"},
	{0x0C, L"Power-on Count"},
	{0xAF, L"Program Fail Count (Chip)"},
	{0xB0, L"Erase Fail Count (Chip)"},
	{0xB1, L"Wear Leveling Count"},
	{0xB2, L"Used Reserved Block Count (Chip)"},
	{0xB3, L"Used Reserved Block Count (Total)"},
	{0xB4, L"Unused Reserved Block Count (Total)"},
	{0xB5, L"Program Fail Count (Total)"},
	{0xB6, L"Erase Fail Count (Total)"},
	{0xB7, L"Runtime Bad Block (Total)"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBE, L"Airflow Temperature"},
	{0xC2, L"Temperature"},
	{0xC3, L"ECC Error Rate"},
	{0xC6, L"Off-Line Uncorrectable Error Count"},
	{0xC7, L"CRC Error Count"},
	{0xC9, L"Super cap Status"},
	{0xCA, L"SSD Mode Status"},
	{0xEB, L"POR Recovery Count"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
	{0xAA, L"Unused Reserved Block Count (Chip) "},
	{0xAB, L"Program Fail Count (Chip)"},
	{0xAC, L"Erase Fail Count (Chip)"},
	{0xAD, L"Wear Leveling Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB8, L"Error Detection"},
	{0xE9, L"Normalized Media Wear-out"},
};

static SMART_NAME SMART_NAME_SmartSandForce[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Retired Block Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x0D, L"Soft Read Error Rate"},
	{0x64, L"Gigabytes Erased"},
	{0xAA, L"Reserve Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB1, L"Wear Range Delta"},
	{0xB5, L"Program Fail Count"},
	{0xB6, L"Erase Fail Count"},
	{0xB8, L"Reported I/O Error Detection Code Errors"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xC2, L"Temperature"},
	{0xC3, L"On-the-Fly ECC Uncorrectable Error Count"},
	{0xC4, L"Reallocation Event Count"},
	{0xC6, L"Uncorrectable Sector Count"},
	{0xC7, L"SATA R-Errors Error Count"},
	{0xC9, L"Uncorrectable Soft Read Error Rate"},
	{0xCC, L"Soft ECC Correction Rate"},
	{0xE6, L"Drive Life Protection Status"},
	{0xE7, L"SSD Life Left"},
	{0xE8, L"Available Reserved Space"},
	{0xEB, L"Power Fail Backup Health"},
	{0xF1, L"Lifetime Writes from Host"},
	{0xF2, L"Lifetime Reads from Host"},
};

static SMART_NAME SMART_NAME_SmartJMicron61x[] =
{
	{0x01, L"Read Error Rate"},
	{0x02, L"Throughput Performance"},
	{0x03, L"Spin-Up Time"},
	{0x05, L"Reallocated Sectors Count"},
	{0x07, L"Seek Error Rate"},
	{0x08, L"Seek Time Performance"},
	{0x09, L"Power-On Hours"},
	{0x0A, L"Spin Retry Count"},
	{0x0C, L"Power Cycle Count"},
	{0xA8, L"SATA PHY Error Count"},
	{0xAF, L"Bad Cluster Table Count (ECC Fail Count)"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xC5, L"Current Pending Sector Count"},
	{0xAA, L"Bad Block Count"},
	{0xAD, L"Erase Count"},
};

static SMART_NAME SMART_NAME_SmartMicron[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reallocated NAND Blocks"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x0D, L"Soft Error Rate"},
	{0x0E, L"Device Capacity (NAND)"},
	{0x0F, L"User Capacity"},
	{0x10, L"Spare Blocks Available"},
	{0x11, L"Remaining Spare Blocks"},
	{0x64, L"Total Erase Count"},
	{0xAA, L"Reserved Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average Block-Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB4, L"Unused Reserve NAND Blocks"},
	{0xB5, L"Unaligned Access Count"},
	{0xB7, L"SATA Interface Downshift"},
	{0xB8, L"Error Correction Count"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xBC, L"Command Timeout Count"},
	{0xBD, L"Factory Bad Block Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"Cumulative ECC Bit Correction Count"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Current Pending Sector Count"},
	{0xC6, L"Smart Off-line Scan Uncorrectable Error Count"},
	{0xC7, L"Ultra DMA CRC Error Rate"},
	{0xCA, L"Percent Lifetime Used"},
	{0xCE, L"Write Error Rate"},
	{0xD2, L"Successful RAIN Recovery Count"},
	{0xEA, L"Total Bytes Read"},
	{0xF2, L"Write Protect Progress"},
	{0xF3, L"ECC Bits Corrected"},
	{0xF4, L"ECC Cumulative Threshold Events"},
	{0xF5, L"Cumulative Program NAND Pages"},
	{0xF6, L"Total Host Sector Writes"},
	{0xF7, L"Host Program Page Count"},
	{0xF8, L"Background Program Page Count"},
	{0xF9, L"Total Refresh ISP Count"},
	{0xFA, L"Total Do RefCal Count"},
	{0xFB, L"Total NAND Read Plane Count (Low 4Bytes)"},
	{0xFC, L"Total NAND Read Plane Count (High 4Bytes)"},
	{0xFD, L"Total Block ReMap Pass Count"},
	{0xFE, L"Total Background Scan Over Limit Count"},
	{0xDF, L"Total Background Scan"},
};

static SMART_NAME SMART_NAME_SmartMicronMU02[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reallocated Sectors Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x0D, L"Soft Error Rate"},
	{0x0E, L"Device Capacity (NAND)"},
	{0x0F, L"User Capacity"},
	{0x10, L"Spare Blocks Available"},
	{0x11, L"Remaining Spare Blocks"},
	{0x64, L"Total Erase Count"},
	{0xAA, L"Reserved Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average Block-Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB4, L"Unused Reserve NAND Blocks"},
	{0xB7, L"SATA Interface Downshift"},
	{0xB8, L"Error Correction Count"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xBC, L"Command Timeout Count"},
	{0xBD, L"Factory Bad Block Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"Cumulative ECC Bit Correction Count"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Current Pending Sector Count"},
	{0xC6, L"Smart Off-line Scan Uncorrectable Error Count"},
	{0xC7, L"Ultra DMA CRC Error Rate"},
	{0xCA, L"Percent Lifetime Used"},
	{0xCE, L"Write Error Rate"},
	{0xD2, L"Successful RAIN Recovery Count"},
	{0xEA, L"Total Bytes Read"},
	{0xF3, L"ECC Bits Corrected"},
	{0xF4, L"ECC Cumulative Threshold Events"},
	{0xF5, L"Cumulative Program NAND Pages"},
	{0xF6, L"Total Host Sector Writes"},
	{0xF7, L"Host Program Page Count"},
	{0xF8, L"Background Program Page Count"},
	{0xA0, L"Uncorrectable Sector Count"},
	{0xA1, L"Valid Spare Blocks"},
	{0xA3, L"Initial Invalid Blocks"},
	{0x94, L"Total SLC Erase Count"},
	{0x95, L"Maximum SLC Erase Count"},
	{0x96, L"Minimum SLC Erase Count"},
	{0x97, L"Average SLC Erase Count"},
	{0xA4, L"Total NAND Erase Count"},
	{0xA5, L"Maximum NAND Erase Count"},
	{0xA6, L"Minimum NAND Erase Count"},
	{0xA7, L"Average NAND Erase Count"},
	{0xA9, L"Percentage Lifetime Remaining"},
	{0xB5, L"Program Fail Count"},
	{0xB6, L"Erase Fail Count"},
	{0xC0, L"Power-off Retract Count"},
	{0xE8, L"Available Reserved Space"},
	{0xF1, L"Total LBA Write"},
	{0xF2, L"Total LBA Read"},
	{0xF5, L"Total NAND Write Count"},
	{0xF6, L"Total SLC Write Count"},
	{0xF7, L"RAID Recovery Count"},
	{0xF9, L"Total Refresh ISP Count"},
	{0xFA, L"Total Do RefCal Count"},
	{0xFB, L"Total NAND Read Plane Count (Low 4Bytes)"},
	{0xFC, L"Total NAND Read Plane Count (High 4Bytes)"},
	{0xFD, L"Total Block ReMap Pass Count"},
	{0xFE, L"Total Background Scan Over Limit Count"},
	{0xDF, L"Total Background Scan"},
};

static SMART_NAME SMART_NAME_SmartOcz[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x03, L"Spin Up Time"},
	{0x04, L"Start Stop Count"},
	{0x05, L"Reallocated Sectors Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xC2, L"Temperature"},
	{0xE8, L"Total Count of Write Sectors"},
	{0xE9, L"Remaining Life"},
	{0x64, L"Total Blocks Erased"},
	{0xA7, L"SSD Protect Mode"},
	{0xA8, L"SATA PHY Error Count"},
	{0xA9, L"Bad Block Count"},
	{0xAD, L"Erase Count"},
	{0xB8, L"Factory Bad Block Count"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xCA, L"Total Number of Corrected Bits"},
	{0xCD, L"Max Rated PE Counts"},
	{0xCE, L"Minimum Erase Counts"},
	{0xCF, L"Maximum Erase Counts"},
	{0xD3, L"SATA Uncorrectable Error Count"},
	{0xD4, L"NAND Page Reads During Retry"},
	{0xD5, L"Simple Read Retry Attempts"},
	{0xD6, L"Adaptive Read Retry Attempts"},
	{0xDD, L"Internal Data Path Uncorrectable Errors"},
	{0xDE, L"RAID Recovery Count"},
	{0xE6, L"Power Loss Protection"},
	{0xFB, L"NAND Read Count"},
	{0xF1, L"Total Host Writes"},
	{0xF2, L"Total Host Reads"},
	{0xF9, L"Total NAND Writes"},
};

static SMART_NAME SMART_NAME_SmartPlextor[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Reallocated Sectors Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xAA, L"Grown Bad Blocks"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average Program/Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xAF, L"Program Fail Count (Worst Case)"},
	{0xB0, L"Erase Fail Count (Worst Case)"},
	{0xB1, L"Wear Leveling Count"},
	{0xB2, L"Used Reserved Block Count (Worst Case)"},
	{0xB3, L"Used Reserved Block Count"},
	{0xB4, L"UnUsed Reserved Block Count (Total)"},
	{0xB5, L"Program Fail Count"},
	{0xB6, L"Erase Fail Count"},
	{0xB7, L"SATA Interface Down Shift"},
	{0xB8, L"End-to-End Data Errors Corrected"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBC, L"Command Time out"},
	{0xC0, L"Unsafe Shutdown Count"},
	{0xC3, L"ECC rate"},
	{0xC4, L"Reallocation Event Count"},
	{0xC6, L"Uncorrectable Sector Count"},
	{0xC7, L"Ultra CRC Error Count"},
	{0xE8, L"Available Reserved Space"},
	{0xE9, L"NAND GB written"},
	{0xF1, L"Total Host Writes"},
	{0xF2, L"Total Host Reads"},
};

static SMART_NAME SMART_NAME_SmartSanDisk[] =
{
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xAA, L"Reserve Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average Write/Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xC2, L"Temperature"},
	{0xE6, L"Percent of Total Write/Erase Count"},
	{0xE8, L"Spare Blocks Remaining"},
	{0xEA, L"Percent of Total Write/Erase Count (BC blocks)"},
	{0xF1, L"Total Host Writes"},
	{0xF2, L"Total Host Reads"},
};

static SMART_NAME SMART_NAME_SmartOczVector[] =
{
	{0x05, L"Accumulated Runtime Bad Blocks"},
	{0x09, L"Power-On Hours Count"},
	{0x0C, L"Power Cycle Count"},
	{0xAB, L"Available Over-Provisioned Block Count"},
	{0xAE, L"Power Cycle Count (Unplanned)"},
	{0xBB, L"Total Uncorrectable NAND Reads"},
	{0xC2, L"Temperature"},
	{0xC3, L"Total Programming Failures"},
	{0xC4, L"Total Erase Failures"},
	{0xC5, L"Total Read Failures (Uncorrectable)"},
	{0xC6, L"Host Reads"},
	{0xC7, L"Host Writes"},
	{0xD0, L"Average Erase Count"},
	{0xD2, L"SATA CRC Error Count"},
	{0xE9, L"Remaining Life"},
	{0xF9, L"Total NAND Programming Count"},
	{0xF1, L"Total Host Writes"},
	{0xF2, L"Total Host Reads"},
	{0x64, L"Total Blocks Erased"},
	{0xB8, L"Factory Bad Block Count Total"},
	{0xCA, L"Total Number Of Read Bits Corrected"},
	{0xCD, L"Max Rated PE Count"},
	{0xCE, L"Min Erase Count"},
	{0xCF, L"Max Erase Count"},
	{0xD4, L"Total Count NAND Pages Reads Requiring Read Retry"},
	{0xD5, L"Total Count of Simple Read Retry Attempts"},
	{0xD6, L"Total Count of Adaptive Read Retry Attempts"},
	{0xDD, L"Internal Data Path Protection Uncorrectable Errors"},
	{0xDE, L"RAID Recovery Count"},
	{0xE0, L"In Warranty"},
	{0xE1, L"DAS Polarity"},
	{0xE2, L"Partial Pfail"},
	{0xE6, L"Write Throttling Activation Flag"},
	{0xF9, L"Total NAND Programming Count (pages)"},
	{0xFB, L"Total NAND Read Count"},
};

static SMART_NAME SMART_NAME_SmartCorsair[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Retired Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xAA, L"Reserve Block Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB5, L"Program Fail Count"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocation Event Count"},
	{0xE7, L"SSD Life Left"},
	{0xF1, L"Lifetime Written"},
	{0xF2, L"Lifetime Read"},
};

static SMART_NAME SMART_NAME_SmartToshiba[] =
{
	{0x01, L"Read Error Rate"},
	{0x02, L"Throughput Performance"},
	{0x03, L"Spin-Up Time"},
	{0x04, L"Start/Stop Count"},
	{0x05, L"Reallocated Sectors Count"},
	{0x07, L"Seek Error Rate"},
	{0x08, L"Seek Time Performance"},
	{0x09, L"Power-On Hours"},
	{0x0A, L"Spin Retry Count"},
	{0x0B, L"Recalibration Retries"},
	{0x0C, L"Power Cycle Count"},
	{0xA7, L"SSD Protect Mode"},
	{0xA8, L"SATA PHY Error Count"},
	{0xA9, L"Total Bad Block Count"},
	{0xAD, L"Erase Count"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Current Pending Sector Count"},
	{0xC6, L"Uncorrectable Sector Count"},
	{0xF1, L"Total Host Writes"},
	{0xF2, L"Total Host Reads"},
};

static SMART_NAME SMART_NAME_SmartSanDiskGb[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xA5, L"Block Erase Count (SLC)"},
	{0xA6, L"Minimum P/E Cycles"},
	{0xA7, L"Maximum Bad Blocks per die"},
	{0xA8, L"Maximum P/E Cycles"},
	{0xA9, L"Total Bad Block"},
	{0xAA, L"Grown Bad Blocks"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average P/E Cycles"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB8, L"End-to-End Error Detection/Correction Count"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xBC, L"Command Timeout Count"},
	{0xC2, L"Temperature"},
	{0xC7, L"CRC Error Count"},
	{0xD4, L"SATA PHY Error"},
	{0xE6, L"Media Wearout Indicator"},
	{0xE7, L"SSD Life Left"},
	{0xE8, L"Available Reserve Space"},
	{0xE9, L"NAND GB Written"},
	{0xEA, L"NAND GB Written (SLC)"},
	{0xEE, L"Media Wearout Indicator (Cycles Remaining)"},
	{0xF1, L"Total GB Written"},
	{0xF2, L"Total GB Read"},
	{0xF4, L"Temperature Throttle Status"},
	{0xF9, L"NAND GB Written"},
};

static SMART_NAME SMART_NAME_SmartKingston[] =
{
	{0x01, L"Read Error Rate"},
	{0x02, L"Throughput Performance"},
	{0x03, L"Spin Up Time"},
	{0x05, L"Reallocated Sectors Count"},
	{0x07, L"Seek Error Rate"},
	{0x08, L"Seek Time Performance"},
	{0x09, L"Power-On Hours"},
	{0x0A, L"Spin Retry Count"},
	{0x0C, L"Power Cycle Count"},
	{0xA8, L"SATA PHY Error Count"},
	{0xAA, L"Bad Block Count"},
	{0xAD, L"Erase count"},
	{0xAF, L"Bad Cluster Table Count"},
	{0xBB, L"Uncorrectable Errors"},
	{0xC0, L"Unsafe Shutdown Count"},
	{0xC2, L"Temperature"},
	{0xC4, L"Later Bad Block Count"},
	{0xC5, L"Current Pending Sector Count"},
	{0xC7, L"CRC Error Count"},
	{0xDA, L"CRC Error Count"},
	{0xE7, L"SSD Life Left"},
	{0xE9, L"Lifetime Writes to Flash"},
	{0xF0, L"Write Head"},
	{0xF1, L"Host Writes"},
	{0xF2, L"Host Reads"},
	{0xF4, L"Average Erase Count"},
	{0xF5, L"Max Erase Count"},
	{0xF6, L"Total Erase Count"},
};

static SMART_NAME SMART_NAME_SmartNVMe[] =
{
	{0x01, L"Critical Warning"},
	{0x02, L"Composite Temperature"},
	{0x03, L"Available Spare"},
	{0x04, L"Available Spare Threshold"},
	{0x05, L"Percentage Used"},
	{0x06, L"Data Units Read"},
	{0x07, L"Data Units Written"},
	{0x08, L"Host Read Commands"},
	{0x09, L"Host Write Commands"},
	{0x0A, L"Controller Busy Time"},
	{0x0B, L"Power Cycles"},
	{0x0C, L"Power On Hours"},
	{0x0D, L"Unsafe Shutdowns"},
	{0x0E, L"Media and Data Integrity Errors"},
	{0x0F, L"Number of Error Information Log Entries"},
	{0x10, L"Warning Composite Temperature Time"},
	{0x11, L"Critical Composite Temperature Time"},
	{0x12, L"Temperature Sensor 1"},
	{0x13, L"Temperature Sensor 2"},
	{0x14, L"Temperature Sensor 3"},
	{0x15, L"Temperature Sensor 4"},
	{0x16, L"Temperature Sensor 5"},
	{0x17, L"Temperature Sensor 6"},
	{0x18, L"Temperature Sensor 7"},
	{0x19, L"Temperature Sensor 8"},
	{0x1A, L"Thermal Management Temperature 1 Transition Count"},
	{0x1B, L"Thermal Management Temperature 2 Transition Count"},
	{0x1C, L"Total Time For Thermal Management Temperature 1"},
	{0x1D, L"Total Time For Thermal Management Temperature 2"},
};

static SMART_NAME SMART_NAME_SmartRealtek[] =
{
	{0x01, L"Raw data error rate"},
	{0x05, L"Reallocated sector count"},
	{0x09, L"Power on hour count"},
	{0x0C, L"Power cycle count"},
	{0xA1, L"GDN"},
	{0xA2, L"Total erase count"},
	{0xA3, L"Max PE cycle"},
	{0xA4, L"Average erase count"},
	{0xA5, L"Initial bad block count"},
	{0xA6, L"Total bad block count"},
	{0xA7, L"SSD protect mode"},
	{0xA8, L"SATA Phy error count"},
	{0xA9, L"Health"},
	{0xAB, L"Program fail count"},
	{0xAC, L"Erase fail count"},
	{0xAE, L"Unexpected power loss count"},
	{0xAF, L"ECC fail count"},
	{0xB5, L"Unaligned access count"},
	{0xBB, L"Reported uncorrectable error"},
	{0xC2, L"Enclosure temperature"},
	{0xC3, L"Cumulative corrected ecc"},
	{0xC4, L"Reallocation event count"},
	{0xC7, L"Ultra DMA CRC error count"},
	{0xCE, L"Min. erase count"},
	{0xCF, L"Max erase count"},
	{0xE7, L"Lifetime left"},
	{0xE8, L"Available reserved space"},
	{0xF1, L"Write life time"},
	{0xF2, L"Read life time"},
	{0xF9, L"Total GB written to NAND"},
	{0xFA, L"Total GB written to NAND (SLC)"},
};

static SMART_NAME SMART_NAME_SmartSKhynix[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Re-Assigned Sector Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x64, L"Total Erase Count"},
	{0xA8, L"Min. Erase Count"},
	{0xA9, L"Max. Erase Count"},
	{0xAA, L"Reserve Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xAF, L"Program Fail Count(Worst Case)"},
	{0xB0, L"Erase Fail Count(Worst Case)"},
	{0xB1, L"Wear Leveling Count"},
	{0xB2, L"Used Reseved Block Count(Worst Case)"},
	{0xB3, L"Used Reseved Block Count(SSD Total)"},
	{0xB4, L"UnUsed Reseved Block Count(SSD Total)"},
	{0xB5, L"Program Fail Count(SSD Total)"},
	{0xB6, L"Erase Fail Count(SSD Total)"},
	{0xB7, L"SATA Downshift Count"},
	{0xB8, L"End-to-End Error Detection Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBC, L"Command Timeout Count"},
	{0xBF, L"Op Shock Event Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"ECC Rate"},
	{0xC4, L"Reallocation Event Count"},
	{0xC6, L"Uncorrectable Sector Count"},
	{0xC7, L"CRC Error Count"},
	{0xC9, L"Uncorrectable Soft Read Error Rate"},
	{0xCC, L"Soft ECC Correction Rate"},
	{0xD4, L"Phy Error Count"},
	{0xE7, L"SSD Life Left"},
	{0xE9, L"SSD Life Left"},
	{0xEA, L"NAND Written"},
	{0xF1, L"Total LBA Written"},
	{0xF2, L"Total LBA Read"},
	{0xFA, L"Total Number of NAND Read Retries"},
};

static SMART_NAME SMART_NAME_SmartKioxia[] =
{
	{0x09, L"Power-On Hours Count"},
	{0x0C, L"Power Cycle Count"},
	{0xA7, L"SSD Protect Mode"},
	{0xA8, L"SATA PHY Error Count"},
	{0xA9, L"Bad Block Count"},
	{0xAD, L"Erase Count (User Data)"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xF1, L"Host Writes"},
};

static SMART_NAME SMART_NAME_SmartWdc[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xA5, L"Block Erase Count (SLC)"},
	{0xA6, L"Minimum P/E Cycles"},
	{0xA7, L"Maximum Bad Blocks per die"},
	{0xA8, L"Maximum P/E Cycles"},
	{0xA9, L"Total Bad Block"},
	{0xAA, L"Grown Bad Blocks"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average P/E Cycles"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB8, L"End-to-End Error Detection/Correction Count"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xBC, L"Command Timeout Count"},
	{0xC2, L"Temperature"},
	{0xC7, L"CRC Error Count"},
	{0xD4, L"SATA PHY Error"},
	{0xE6, L"Media Wearout Indicator"},
	{0xE8, L"Available Reserve Space"},
	{0xE9, L"NAND GB Written"},
	{0xEA, L"NAND GB Written (SLC)"},
	{0xEE, L"Media Wearout Indicator (Cycles Remaining)"},
	{0xF1, L"Total GB Written"},
	{0xF2, L"Total GB Read"},
	{0xF3, L"Total NAND Writes"},
	{0xF4, L"Temperature Throttle Status"},
	{0xF9, L"NAND GB Written"},
};

static SMART_NAME SMART_NAME_SmartKingstonSuv[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Reallocated Sector Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xAA, L"Used Reserved Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAE, L"Unexpected Power Off Count"},
	{0xAF, L"Program Fail Count Worst Die"},
	{0xB0, L"Erase Fail Count Worst Die"},
	{0xB1, L"Wear Leveling Count"},
	{0xB2, L"Used Reserved Block Count worst Die"},
	{0xB4, L"Unused Reserved Block Count (SSD Total)"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xC2, L"Temperature"},
	{0xC3, L"On-the-Fly ECC Error Count"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Pending Sector Count"},
	{0xC7, L"UDMA CRC Error Count"},
	{0xC9, L"Uncorrectable Read Error Rate"},
	{0xCC, L"Soft ECC Correction Rate"},
	{0xE7, L"SSD Life Left"},
	{0xEA, L"Lifetime Nand Writes"},
	{0xF1, L"Lifetime Host Writes"},
	{0xF2, L"Lifetime Host Reads"},
	{0xFA, L"Total Number of NAND Read Retries"},
};

static SMART_NAME SMART_NAME_SmartKingstonKC600[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Re-Allocated NAND Block Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x94, L"Reserved"},
	{0x95, L"Reserved"},
	{0x96, L"Reserved"},
	{0x97, L"SLC Average Erase Count"},
	{0x9F, L"DRAM 1 bit Error Count"},
	{0xA0, L"Reported UECC (UnCorrectable) Errors"},
	{0xA1, L"Available Reserved Space"},
	{0xA4, L"Reserved"},
	{0xA5, L"Reserved"},
	{0xA6, L"Reserved"},
	{0xA7, L"Average Erase Count"},
	{0xA8, L"Reserved"},
	{0xA9, L"Percentage Of Rated Lifetime Remaining"},
	{0xB1, L"Reserved"},
	{0xB5, L"Program Fail Count"},
	{0xB6, L"Erase Fail Count"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Device Temperature"},
	{0xC3, L"Hardware ECC Recovered"},
	{0xC4, L"Reallocation Event Count"},
	{0xC7, L"UDMA CRC Error Count"},
	{0xE7, L"Percentage of Rated Lifetime Remaining"},
	{0xE8, L"Unused Reserved Block Count"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
	{0xF5, L"Total Media Writes"},
};

static SMART_NAME SMART_NAME_SmartKingstonDC500[] =
{
	{0x01, L"Host UNC Error Count"},
	{0x09, L"Power on Hours"},
	{0x0C, L"Power On / Off Cycle"},
	{0xA7, L"Protect mode"},
	{0xA8, L"SATA PHY Error Count"},
	{0xA9, L"Bad Block Rate"},
	{0xAA, L"Bad Block Information"},
	{0xAC, L"Erase Failure Count"},
	{0xAD, L"Erase Count"},
	{0xB5, L"Program Fail Count"},
	{0xB6, L"Erase Failure Count"},
	{0xBB, L"Host UNC Error Count"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xC4, L"Total Later Bad Block Count"},
	{0xC7, L"CRC Error Count"},
	{0xCF, L"Thermal Throttling Count"},
	{0xDA, L"CRC Error Count"},
	{0xE7, L"SSD Life Remaining"},
	{0xE8, L"Read Fail Count"},
	{0xE9, L"NAND Write"},
	{0xF1, L"Host Write"},
	{0xF2, L"Host Read"},
	{0xF4, L"Avg Erase Count"},
	{0xF5, L"Max Erase Count"},
	{0xF6, L"Total Erase Count"},
};

static SMART_NAME SMART_NAME_SmartKingstonSA400[] =
{
	{0x01, L"Uncorrectable Errors"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycles"},
	{0x94, L"Vendor Unique"},
	{0x95, L"Vendor Unique"},
	{0xA7, L"Vendor Unique"},
	{0xA8, L"SATA PHY Error Count"},
	{0xA9, L"Vendor Unique"},
	{0xAA, L"Bad Block Count"},
	{0xAC, L"Vendor Unique"},
	{0xAD, L"Erase Count"},
	{0xB5, L"Vendor Unique"},
	{0xB6, L"Vendor Unique"},
	{0xBB, L"Uncorrectable ECC Errors"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocation Events"},
	{0xC7, L"SATA CRC Error"},
	{0xDA, L"CRC Error Count"},
	{0xE7, L"SSD Wear Indicator"},
	{0xE9, L"Lifetime Nand Writes"},
	{0xF1, L"Lifetime Writes from Host"},
	{0xF2, L"Lifetime Read from Host"},
	{0xF4, L"Average Erase Count"},
	{0xF5, L"Max Erase Count"},
	{0xF6, L"Total Erase Count"},
};

static SMART_NAME SMART_NAME_SmartSsstc[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reallocated Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xAA, L"Available Reserved Space"},
	{0xAB, L"Program Fail Count (Total)"},
	{0xAC, L"Erase Fail Count (Total)"},
	{0xAD, L"Average Program/Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xAF, L"Program Fail count (Worst case)"},
	{0xB0, L"Erase Fail Count (Worst case)"},
	{0xB1, L"Wear Leveling Count"},
	{0xB2, L"Used Reserved Block Count (Worst case)"},
	{0xB3, L"Used Reserved Block Count (Total)"},
	{0xB4, L"Unused Reserved Block Count (Total)"},
	{0xB7, L"SATA Interface Down shift"},
	{0xB8, L"End-to-End Data Errors Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBC, L"Command Time out"},
	{0xC2, L"Drive Temperature"},
	{0xC3, L"ECC rate"},
	{0xC6, L"OffLine Uncorrectable Error Count"},
	{0xC7, L"SATA CRC Error Count"},
	{0xE5, L"Power Loss Protection Failure"},
	{0xE7, L"Percentage Lifetime Remaining"},
	{0xE8, L"Available Reserved Space "},
	{0xE9, L"NAND GB Written"},
	{0xF1, L"Total Host Write"},
	{0xF2, L"Total Host Read "},
	{0xF3, L"NAND GB Written"},
};

static SMART_NAME SMART_NAME_SmartIntelDc[] =
{

	{0x01, L"Raw Read Error Count"},
	{0x05, L"Reallocated Flash Block Count"},
	{0x09, L"Power-On Hours Count"},
	{0x0C, L"Power Cycle Count"},
	{0x0E, L"Device Capacity"},
	{0x0F, L"User Capacity"},
	{0x10, L"Spare Blocks Available"},
	{0x11, L"Remaining Spare Available"},
	{0xAC, L"Total Block Erase Failure"},
	{0xAD, L"Per Block Max Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xAF, L"Average Erase Count"},
	{0xB0, L"Power Loss Protection Error"},
	{0xB5, L"Total Block Program Failure"},
	{0xB8, L"End-to-End Error Detection Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xC2, L"Temperature"},
	{0xC5, L"Pending Sector Count"},
	{0xC6, L"Offline Uncorrectable Error Count"},
	{0xC7, L"CRC Error Count"},
	{0xCA, L"Percentage of Drive Life Used"},
	{0xE2, L"Timed Workload - Media Wear"},
	{0xE3, L"Timed Workload - Host Read/Write Ratio"},
	{0xE4, L"Timed Workload Timer"},
	{0xEA, L"Thermal Throttle Status"},
	{0xEB, L"Total Host Bytes/Sectors Written"},
	{0xF1, L"Total Nand Bytes/Sectors Written"},
};

static SMART_NAME SMART_NAME_SmartApacer[] =
{
	{0x09, L"Power on Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xA3, L"Maximum Erase Count"},
	{0xA4, L"Average Erase Count"},
	{0xA6, L"Total Later Bad Block Count"},
	{0xA7, L"SSD Protect Mode"},
	{0xA8, L"SATA PHY Error Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAF, L"Bad Cluster Table Count"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xE7, L"Lifetime Left"},
	{0xF1, L"Total Sectors Write"},
};

static SMART_NAME SMART_NAME_SmartSiliconMotion[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Reallocated Sectors Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x94, L"SLC Total Erase Count"},
	{0x95, L"SLC Maximum Erase Count"},
	{0x96, L"SLC Minimum Erase Count"},
	{0x97, L"SLC Average Erase Count"},
	{0x9F, L"DRAM 1 bit Error Count"},
	{0xA0, L"Uncorrectable sectors count when read/write"},
	{0xA1, L"Number of Valid Spare Blocks"},
	{0xA2, L"Number of Cache Data Block"},
	{0xA3, L"Number of Initial Invalid Blocks"},
	{0xA4, L"Total Erase Count"},
	{0xA5, L"Maximum Erase Count"},
	{0xA6, L"Minimum Erase Count"},
	{0xA7, L"Average Erase Count"},
	{0xA8, L"Max Erase Count of Spec"},
	{0xA9, L"Remain Life"},
	{0xAF, L"Program fail count in worst die"},
	{0xB0, L"Erase fail count in worst die"},
	{0xB1, L"Total Wear Level Count"},
	{0xB2, L"Runtime Invalid Block Count"},
	{0xB5, L"Total Program Fail Count"},
	{0xB6, L"Total Erase Fail Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xC0, L"Power-Off Retract Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"Hardware ECC Recovered"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Current Pending Sector Count"},
	{0xC6, L"Uncorrectable Error Count Off-line"},
	{0xC7, L"Ultra DMA CRC Error Count"},
	{0xE8, L"Available Reserved Space"},
	{0xF1, L"Total LBA Written"},
	{0xF2, L"Total LBA Read"},
	{0xF5, L"Flash Write Sector Count"},
};

static SMART_NAME SMART_NAME_SmartJMicron66x[] =
{
	{0x01, L"Read Error Rate"},
	{0x02, L"Throughput Performance"},
	{0x03, L"Spin-Up Time"},
	{0x05, L"Reallocated Sectors Count"},
	{0x07, L"Seek Error Rate"},
	{0x08, L"Seek Time Performance"},
	{0x09, L"Power-On Hours"},
	{0x0A, L"Spin Retry Count"},
	{0x0C, L"Power Cycle Count"},
	{0xA7, L"SSD Protect Mode"},
	{0xA8, L"SATA PHY Error Count"},
	{0xAA, L"Bad Block Count"},
	{0xAD, L"Erase Count"},
	{0xAF, L"Bad Cluster Table Count"},
	{0xB4, L"Spare Block Count"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xC5, L"Current Pending Sector Count"},
	{0xE7, L"Drive Life"},
	{0xE9, L"Write Sector Count (NAND)"},
	{0xF0, L"Write Head"},
	{0xF1, L"Total LBA Written"},
	{0xF2, L"Total LBA Read"},
};

static SMART_NAME SMART_NAME_SmartPhison[] =
{
	{0x01, L"Read Error Rate"},
	{0x09, L"Power on Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xA8, L"SATA PHY Error Count"},
	{0xAA, L"Bad Block Count"},
	{0xAD, L"Erase Count"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xDA, L"Number of CRC Error"},
	{0xE7, L"SSD Life Left"},
	{0xF1, L"Host Writes"},
};

static SMART_NAME SMART_NAME_SmartSeagate[] =
{
	{0x01, L"Read Error Rate"},
	{0x05, L"Retired Sectors Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x10, L"Spare Blocks Available"},
	{0x11, L"Remaining Spare Blocks"},
	{0xA8, L"SATA PHY Error Count"},
	{0xAA, L"Bad Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB1, L"Wear Range Delta"},
	{0xB5, L"Program Fail Count"},
	{0xB6, L"Erase Fail Count"},
	{0xC0, L"Unexpected Power loss Count"},
	{0xC2, L"Temperature"},
	{0xC9, L"Soft Error Rate"},
	{0xCC, L"Soft ECC Correction Rate"},
	{0xDA, L"CRC Error Count"},
	{0xE7, L"SSD Life Left"},
	{0xE8, L"Read Failure Block Count"},
	{0xE9, L"NAND GiB Written"},
	{0xEA, L"Lifetime Writes To Flash"},
	{0xEB, L"NAND sectors Written"},
	{0xF1, L"Lifetime Writes From Host"},
	{0xF2, L"Lifetime Reads From Host"},
	{0xFA, L"Lifetime NAND Read Retries"},
};

static SMART_NAME SMART_NAME_SmartSeagateIronWolf[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reallocated Sector Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x64, L"Flash Gigabytes Erased"},
	{0x66, L"Lifetime PS4 Entry Count"},
	{0x67, L"Lifetime PS3 Entry Count"},
	{0xAA, L"Grown Bad Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average Program/Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB1, L"Wear Range Delta"},
	{0xB7, L"SATA/PCIe Interface Downshift Count"},
	{0xBB, L"Uncorrectable ECC Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"RAISE ECC Correctable Count"},
	{0xC6, L"Uncorrectable Read Error Count"},
	{0xC7, L"SATA R-Error (CRC) Error Count"},
	{0xE6, L"Drive Life Protection Status"},
	{0xE7, L"SSD Life Left"},
	{0xE8, L"Available Reserved Space"},
	{0xE9, L"Lifetime Writes to Flash"},
	{0xF1, L"Lifetime Writes From Host"},
	{0xF2, L"Lifetime Reads From Host"},
	{0xF3, L"Free Space"},
};

static SMART_NAME SMART_NAME_SmartMarvell[] =
{
	{0x05, L"Number of New Bad Block"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xA4, L"Total Erase Count"},
	{0xA5, L"Maximum Erase Count"},
	{0xA6, L"Minimum Erase Count"},
	{0xA7, L"Average Erase Count"},
	{0xC0, L"Power off Retract Count"},
	{0xC2, L"Temperature"},
	{0xC7, L"SATA CRC Error Count"},
	{0xF1, L"Total Written"},
	{0xF2, L"Total Read"},
};

static SMART_NAME SMART_NAME_SmartMaxiotek[] =
{
	{0x05, L"Reallocated Sector Count"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0xA7, L"SSD Protect Mode"},
	{0xA8, L"PHY Error Count"},
	{0xA9, L"Bad Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Erase Count"},
	{0xAF, L"Bad Cluster Table Count"},
	{0xB1, L"Read Retry Count"},
	{0xB4, L"Spare Block Count Left"},
	{0xBB, L"Reported UNC Errors"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocated Event Count"},
	{0xC7, L"UDMA CRC Error Count"},
	{0xCE, L"Minimum Erase Count"},
	{0xCF, L"Maximum Erase Count"},
	{0xD0, L"Average Erase Count"},
	{0xD1, L"Minimum Erase Count of SLC block"},
	{0xD2, L"Maximum Erase Count of SLC block"},
	{0xD3, L"Average Erase Count of SLC block"},
	{0xE7, L"SSD Life Left"},
	{0xE9, L"Write Counts Sectors to Nand"},
	{0xEA, L"Read Counts Sectors from Nand"},
	{0xF1, L"Write Sector Count"},
	{0xF2, L"Read Sector Count"},
	{0xF5, L"Bit Error Count"},
};

static SMART_NAME SMART_NAME_SmartSeagateBarraCuda[] =
{
	{0x01, L"UECC Error Count"},
	{0x05, L"Retired Sectors Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Power Cycle Count"},
	{0x10, L"Spare Blocks Available"},
	{0x11, L"Remaining Spare Blocks"},
	{0xA8, L"SATA PHY Error Count"},
	{0xAA, L"Bad Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB1, L"Wear Range Delta"},
	{0xB5, L"Program Fail Count"},
	{0xB6, L"Erase Fail Count"},
	{0xC0, L"Unexpected Power loss Count"},
	{0xC2, L"Temperature"},
	{0xC9, L"Soft Error Rate"},
	{0xCC, L"Soft ECC Correction Rate"},
	{0xDA, L"CRC Error Count"},
	{0xE7, L"SSD Life Left"},
	{0xE8, L"Read Failure Block Count"},
	{0xE9, L"NAND GiB Written"},
	{0xEA, L"Lifetime Writes To Flash"},
	{0xEB, L"NAND sectors Written"},
	{0xF1, L"Lifetime Writes From Host"},
	{0xF2, L"Lifetime Reads From Host"},
	{0xFA, L"Lifetime NAND Read Retries"},
};

static SMART_NAME SMART_NAME_SmartYmtc[] =
{
	{0x05, L"New Bad Block Count"},
	{0x09, L"Power-On Hours Count"},
	{0x0C, L"Power Cycle Count"},
	{0xAA, L"Max Bad Block Count"},
	{0xA8, L"SATA PHY Error Count"},
	{0xA9, L"Bad Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Erase Count"},
	{0xAF, L"Bad Cluster Count"},
	{0xB7, L"SATA Interface Downshift"},
	{0xB8, L"End to End Error Detection/Correction Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBE, L"Temperature"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC4, L"Re-allocated Event Count"},
	{0xC7, L"CRC Error Count"},
	{0xCE, L"Minimum Erase Count"},
	{0xCF, L"Maximum Erase Count"},
	{0xD0, L"Average Erase Count"},
	{0xD1, L"SLC Minimum Erase Count"},
	{0xD2, L"SLC Maximum Erase Count"},
	{0xD3, L"SLC Average Erase Count"},
	{0xE7, L"SSD Life Left"},
	{0xE9, L"Write sector count to NAND"},
	{0xEA, L"Read sector count to NAND"},
	{0xF1, L"Total LBA written"},
	{0xF2, L"Total LBA Read"},
	{0xF3, L"NAND Temperature"},
	{0xF5, L"Bit Error Count"},
};

static SMART_NAME SMART_NAME_SmartScy[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reallocated Sector Count"},
	{0x07, L"Seek Error Rate"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xA7, L"Average Erase Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Erase Count"},
	{0xB1, L"Read Retry Count"},
	{0xB4, L"Spare Block Count Left"},
	{0xB7, L"Runtime Bad Block"},
	{0xBB, L"Reported UNC Errors"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Controlled Temperature"},
	{0xC3, L"Cumulative ECC Bit Correction Count"},
	{0xC4, L"Reallocated Event Count"},
	{0xC5, L"Current Pending Sector"},
	{0xC7, L"UDMA CRC Error Count"},
	{0xE7, L"SSD Life Left"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
	{0xF5, L"Total Nand Flash Written"},
};

static SMART_NAME SMART_NAME_SmartRecadata[] =
{
	{0x07, L"Seek Error Rate"},
	{0x09, L"Power-On Hours"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xA7, L"Average erase count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Erase Count"},
	{0xB1, L"Read Retry Count"},
	{0xB4, L"Spare Block Count Left"},
	{0xB7, L"Runtime Bad Block"},
	{0xBB, L"Reported UNC Errors"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Controlled temperature"},
	{0xC3, L"Cumulative ECC Bit Correction Count"},
	{0xC4, L"Reallocated Event Count"},
	{0xC5, L"Current Pending Sector"},
	{0xC7, L"UDMA CRC Error Count"},
	{0xE7, L"SSD Life Left"},
	{0xF1, L"Total LBAs written"},
	{0xF2, L"Total LBAs read"},
	{0xF5, L"Total Nand Flash Written"},
};

static SMART_NAME SMART_NAME_SmartSanDiskHp[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xAA, L"Reserved Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Wear Leveling Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB0, L"Unused Reserved Block Count"},
	{0xB7, L"SATA Interface Downshift Count"},
	{0xB8, L"End to End Error Detection/Correction Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBC, L"Command Time Out"},
	{0xBE, L"Airflow Temperature"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocated Event Count"},
	{0xC7, L"CRC Error Count"},
	{0xC9, L"SSD Life Left"},
	{0xE6, L"Media Wearout Indicator"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
	{0xF3, L"Throttle Statistics"},
	{0xF4, L"Temperature Throttle Status"},
	{0xF9, L"TLC NAND GB Writes"},
};

static SMART_NAME SMART_NAME_SmartSanDiskHpVenus[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xAA, L"Reserved Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Wear Leveling Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB0, L"Unused Reserved Block Count"},
	{0xB7, L"SATA Interface Downshift Count"},
	{0xB8, L"End to End Error Detection/Correction Count"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xBC, L"Command Time Out"},
	{0xBE, L"Airflow Temperature"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocated Event Count"},
	{0xC7, L"CRC Error Count"},
	{0xC9, L"SSD Life Left"},
	{0xE6, L"Media Wearout Indicator"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
	{0xF3, L"Total NAND Writes"},
	{0xF4, L"Temperature Throttle Status"},
	{0xF9, L"TLC NAND GB Writes"},
};

static SMART_NAME SMART_NAME_SmartSanDiskDell[] =
{
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xAF, L"Program Fail Count (Worst Case Component)"},
	{0xB0, L"Erase Fail Count (Worst Case Component)"},
	{0xB1, L"Wear Leveling Count"},
	{0xB2, L"Used Reserved Block Count (Worst Case Component)"},
	{0xB3, L"Used Reserved Block Count (SSD Total)"},
	{0xB4, L"Remaining Reserved Block Count (SSD Total)"},
	{0xB5, L"Program Fail Count (SSD Total)"},
	{0xB6, L"Erase Fail Count (SSD Total)"},
	{0xBB, L"Uncorrectable Error Count"},
	{0xC2, L"Temperature"},
	{0xC3, L"ECC Rate"},
	{0xC7, L"CRC Error Count"},
	{0xE6, L"Media Wearout Indicator"},
	{0xEE, L"Media Wearout Indicator (Cycles Remaining)"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
};

static SMART_NAME SMART_NAME_SmartSanDiskLenovo[] =
{
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xA6, L"Minimum P/E Cycles"},
	{0xA7, L"Maximum Bad Blocks per Die"},
	{0xA8, L"Maximum P/E cycles"},
	{0xA9, L"Total Bad Blocks"},
	{0xAA, L"Grown Bad Blocks"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average P/E Cycles Attribute"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB2, L"Used Reserved Block Count"},
	{0xB4, L"Remaining Reserved Block Count"},
	{0xB8, L"End to End Error Detection/Correction Count"},
	{0xBB, L"UECC Count"},
	{0xBC, L"Command Time Out"},
	{0xC2, L"Temperature"},
	{0xC7, L"SATA CRC Errors"},
	{0xD4, L"SATA PHY Errors"},
	{0xE6, L"Media Wearout Indicator"},
	{0xE8, L"Available Reserved Space"},
	{0xE9, L"NAND GB Written"},
	{0xEA, L"NAND GB Written (SLC)"},
	{0xF1, L"Total Host GB Write"},
	{0xF2, L"Total GB Read"},
	{0xF3, L"Throttle Statistics"},
	{0xF4, L"Thermal Throttle Status"},
};

static SMART_NAME SMART_NAME_SmartSanDiskLenovoHelenVenus[] =
{
	{0x05, L"Reassigned Block Count"},
	{0x09, L"Power On Hours"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xA6, L"Minimum P/E Cycles"},
	{0xA7, L"Maximum Bad Blocks per Die"},
	{0xA8, L"Maximum P/E cycles"},
	{0xA9, L"Total Bad Blocks"},
	{0xAA, L"Grown Bad Blocks"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average P/E Cycles Attribute"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB2, L"Used Reserved Block Count"},
	{0xB4, L"Remaining Reserved Block Count"},
	{0xB8, L"End to End Error Detection/Correction Count"},
	{0xBB, L"UECC Count"},
	{0xBC, L"Command Time Out"},
	{0xC2, L"Temperature"},
	{0xC7, L"SATA CRC Errors"},
	{0xD4, L"SATA PHY Errors"},
	{0xE8, L"Available Reserved Space"},
	{0xE9, L"Media Wearout Indicator"},
	{0xEA, L"NAND GB Written (SLC)"},
	{0xF1, L"Total Host GB Write"},
	{0xF2, L"Total GB Read"},
	{0xF3, L"Throttle Statistics"},
	{0xF4, L"Thermal Throttle Status"},
	{0xF9, L"NAND GB Written (TLC)"},
};

static SMART_NAME SMART_NAME_SmartMicronMU03[] =
{
	{0x01, L"Raw Read Error Rate"},
	{0x05, L"Reallocated NAND Block Count"},
	{0x09, L"Power On Hours Count"},
	{0x0C, L"Power Cycle Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average Block Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB4, L"Unused Spare NAND Blocks"},
	{0xB5, L"Non-4K Aligned Access"},
	{0xB7, L"SATA interface Downshift"},
	{0xB8, L"Error Correction Count"},
	{0xBB, L"Reported Uncorrectable Errors"},
	{0xC2, L"Temperature"},
	{0xC4, L"Reallocation Event Count"},
	{0xC5, L"Current Pending ECC Count"},
	{0xC6, L"SMART Offline Scan Uncorrectable Error Count"},
	{0xC7, L"UDMA CRC Error Count"},
	{0xCA, L"Lifetime Remaining"},
	{0xCE, L"Write Error Rate"},
	{0xD2, L"Successful RAIN Recovery Count"},
	{0xF0, L"Host Program Page Count"},
	{0xF1, L"Total LBAs Written"},
	{0xF2, L"Total LBAs Read"},
	{0xF3, L"Total Program Page Count"},
	{0xF6, L"Cumulative Host Sectors Written"},
	{0xF7, L"Host Program NAND Pages Count"},
	{0xF8, L"FTL Program NAND Pages Count"},
};

static SMART_NAME SMART_NAME_SmartSanDiskCloud[] =
{
	{0x05, L"Retired Block Count"},
	{0x09, L"Power On Hours"},
	{0x0D, L"Count of Uncorrectable ECC Errors"},
	{0x20, L"Write Amplification multiplied by 100"},
	{0x21, L"Write Amplification Factor"},
	{0xAA, L"Reserve Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Average Write/Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xB2, L"SSD Life Left (upto 0.01%)"},
	{0xBF, L"Clean Shutdown Count"},
	{0xC0, L"Unclean Shutdown Count"},
	{0xC2, L"Temperature"},
	{0xC4, L"Number of Blocks Reallocated"},
	{0xE6, L"Percent of Total Write/Erase Count"},
	{0xE8, L"Spare Blocks Remaining"},
	{0xE9, L"Total Nand Writes 64GB"},
	{0xEB, L"Capacitor Health"},
	{0xF1, L"Total Host Writes 64GB"},
	{0xF2, L"Total Host Reads 64GB"},
	{0xF4, L"Lifetime Thermal Throttle Activations"},
	{0xF5, L"Percent Drive Life Remaining"},
	{0xFD, L"SPI Tests Remaining"},
};

static SMART_NAME SMART_NAME_SmartSiliconMotionCVC[] =
{
	{0x05, L"Re-Assigned Count"},
	{0x09, L"Power-On Hours Count"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xA5, L"SLC Cache"},
	{0xAA, L"Grown Bad Block Count"},
	{0xAB, L"Program Fail Count"},
	{0xAC, L"Erase Fail Count"},
	{0xAD, L"Avg Erase Count"},
	{0xAE, L"Unexpected Power Loss Count"},
	{0xAF, L"Program Fail Count (Worst case)"},
	{0xB7, L"Total SATA Link Speed Downshift"},
	{0xB8, L"End-to-End Data Errors corrected"},
	{0xBB, L"Uncorrectable Errors"},
	{0xBD, L"Max Erase Count"},
	{0xBE, L"Temperature"},
	{0xBF, L"Min Erase Count"},
	{0xC3, L"Read Error Rate"},
	{0xC6, L"Off-Line Scan Uncorrectable Sector Count"},
	{0xC7, L"SATA CRC Error Count"},
	{0xCA, L"SSD Life Left"},
	{0xE8, L"Total Spare Counts"},
	{0xE9, L"TLC NAND Write"},
	{0xF1, L"Host Write"},
	{0xF2, L"Host Read"},
	{0x94, L"RAID Event Count"},
	{0x95, L"RAID Uncorrectable Count"},
	{0xA7, L"SSD Protect Mode"},
	{0x93, L"Soft Retry Event Count"},
	{0xEA, L"SLC NAND Write"},
};

static SMART_NAME SMART_NAME_SmartAdataIndustrial[] =
{
	{0x09, L"Power-On hours Count"},
	{0x0C, L"Drive Power Cycle Count"},
	{0xA7, L"SSD Protect Mode"},
	{0xA8, L"SATA PHY Error Count"},
	{0xA9, L"Bad Block Count"},
	{0xAD, L"Erase Count"},
	{0xAF, L"Bad Cluster Table Count"},
	{0xB4, L"Spare block count left"},
	{0xC0, L"Unexpected Power Loss Count"},
	{0xC2, L"Temperature"},
	{0xE7, L"SSD life left"},
	{0xE9, L"Flash Write Sector Count"},
	{0xEA, L"Flash Read Sector Count"},
	{0xF1, L"Write Sector Count"},
	{0xF2, L"Read Sector Count"},
};

static struct
{
	LPCWSTR group;
	SMART_NAME* name;
	size_t count;
} SMART_NAMES[] =
{
	{L"Smart", SMART_NAME_Smart, ARRAYSIZE(SMART_NAME_Smart)},
	{L"SmartSsd", SMART_NAME_SmartSsd, ARRAYSIZE(SMART_NAME_SmartSsd)},
	{L"SmartMtron", SMART_NAME_SmartMtron, ARRAYSIZE(SMART_NAME_SmartMtron)},
	{L"SmartIndilinx", SMART_NAME_SmartIndilinx, ARRAYSIZE(SMART_NAME_SmartIndilinx)},
	{L"SmartJMicron60x", SMART_NAME_SmartJMicron60x, ARRAYSIZE(SMART_NAME_SmartJMicron60x)},
	{L"SmartIntel", SMART_NAME_SmartIntel, ARRAYSIZE(SMART_NAME_SmartIntel)},
	{L"SmartSamsung", SMART_NAME_SmartSamsung, ARRAYSIZE(SMART_NAME_SmartSamsung)},
	{L"SmartSandForce", SMART_NAME_SmartSandForce, ARRAYSIZE(SMART_NAME_SmartSandForce)},
	{L"SmartJMicron61x", SMART_NAME_SmartJMicron61x, ARRAYSIZE(SMART_NAME_SmartJMicron61x)},
	{L"SmartMicron", SMART_NAME_SmartMicron, ARRAYSIZE(SMART_NAME_SmartMicron)},
	{L"SmartMicronMU02", SMART_NAME_SmartMicronMU02, ARRAYSIZE(SMART_NAME_SmartMicronMU02)},
	{L"SmartOcz", SMART_NAME_SmartOcz, ARRAYSIZE(SMART_NAME_SmartOcz)},
	{L"SmartPlextor", SMART_NAME_SmartPlextor, ARRAYSIZE(SMART_NAME_SmartPlextor)},
	{L"SmartSanDisk", SMART_NAME_SmartSanDisk, ARRAYSIZE(SMART_NAME_SmartSanDisk)},
	{L"SmartOczVector", SMART_NAME_SmartOczVector, ARRAYSIZE(SMART_NAME_SmartOczVector)},
	{L"SmartCorsair", SMART_NAME_SmartCorsair, ARRAYSIZE(SMART_NAME_SmartCorsair)},
	{L"SmartToshiba", SMART_NAME_SmartToshiba, ARRAYSIZE(SMART_NAME_SmartToshiba)},
	{L"SmartSanDiskGb", SMART_NAME_SmartSanDiskGb, ARRAYSIZE(SMART_NAME_SmartSanDiskGb)},
	{L"SmartKingston", SMART_NAME_SmartKingston, ARRAYSIZE(SMART_NAME_SmartKingston)},
	{L"SmartNVMe", SMART_NAME_SmartNVMe, ARRAYSIZE(SMART_NAME_SmartNVMe)},
	{L"SmartRealtek", SMART_NAME_SmartRealtek, ARRAYSIZE(SMART_NAME_SmartRealtek)},
	{L"SmartSKhynix", SMART_NAME_SmartSKhynix, ARRAYSIZE(SMART_NAME_SmartSKhynix)},
	{L"SmartKioxia", SMART_NAME_SmartKioxia, ARRAYSIZE(SMART_NAME_SmartKioxia)},
	{L"SmartWdc", SMART_NAME_SmartWdc, ARRAYSIZE(SMART_NAME_SmartWdc)},
	{L"SmartKingstonSuv", SMART_NAME_SmartKingstonSuv, ARRAYSIZE(SMART_NAME_SmartKingstonSuv)},
	{L"SmartKingstonKC600", SMART_NAME_SmartKingstonKC600, ARRAYSIZE(SMART_NAME_SmartKingstonKC600)},
	{L"SmartKingstonDC500", SMART_NAME_SmartKingstonDC500, ARRAYSIZE(SMART_NAME_SmartKingstonDC500)},
	{L"SmartKingstonSA400", SMART_NAME_SmartKingstonSA400, ARRAYSIZE(SMART_NAME_SmartKingstonSA400)},
	{L"SmartSsstc", SMART_NAME_SmartSsstc, ARRAYSIZE(SMART_NAME_SmartSsstc)},
	{L"SmartIntelDc", SMART_NAME_SmartIntelDc, ARRAYSIZE(SMART_NAME_SmartIntelDc)},
	{L"SmartApacer", SMART_NAME_SmartApacer, ARRAYSIZE(SMART_NAME_SmartApacer)},
	{L"SmartSiliconMotion", SMART_NAME_SmartSiliconMotion, ARRAYSIZE(SMART_NAME_SmartSiliconMotion)},
	{L"SmartJMicron66x", SMART_NAME_SmartJMicron66x, ARRAYSIZE(SMART_NAME_SmartJMicron66x)},
	{L"SmartPhison", SMART_NAME_SmartPhison, ARRAYSIZE(SMART_NAME_SmartPhison)},
	{L"SmartSeagate", SMART_NAME_SmartSeagate, ARRAYSIZE(SMART_NAME_SmartSeagate)},
	{L"SmartSeagateIronWolf", SMART_NAME_SmartSeagateIronWolf, ARRAYSIZE(SMART_NAME_SmartSeagateIronWolf)},
	{L"SmartMarvell", SMART_NAME_SmartMarvell, ARRAYSIZE(SMART_NAME_SmartMarvell)},
	{L"SmartMaxiotek", SMART_NAME_SmartMaxiotek, ARRAYSIZE(SMART_NAME_SmartMaxiotek)},
	{L"SmartSeagateBarraCuda", SMART_NAME_SmartSeagateBarraCuda, ARRAYSIZE(SMART_NAME_SmartSeagateBarraCuda)},
	{L"SmartYmtc", SMART_NAME_SmartYmtc, ARRAYSIZE(SMART_NAME_SmartYmtc)},
	{L"SmartScy", SMART_NAME_SmartScy, ARRAYSIZE(SMART_NAME_SmartScy)},
	{L"SmartRecadata", SMART_NAME_SmartRecadata, ARRAYSIZE(SMART_NAME_SmartRecadata)},
	{L"SmartSanDiskHp", SMART_NAME_SmartSanDiskHp, ARRAYSIZE(SMART_NAME_SmartSanDiskHp)},
	{L"SmartSanDiskHpVenus", SMART_NAME_SmartSanDiskHpVenus, ARRAYSIZE(SMART_NAME_SmartSanDiskHpVenus)},
	{L"SmartSanDiskDell", SMART_NAME_SmartSanDiskDell, ARRAYSIZE(SMART_NAME_SmartSanDiskDell)},
	{L"SmartSanDiskLenovo", SMART_NAME_SmartSanDiskLenovo, ARRAYSIZE(SMART_NAME_SmartSanDiskLenovo)},
	{L"SmartSanDiskLenovoHelenVenus", SMART_NAME_SmartSanDiskLenovoHelenVenus, ARRAYSIZE(SMART_NAME_SmartSanDiskLenovoHelenVenus)},
	{L"SmartMicronMU03", SMART_NAME_SmartMicronMU03, ARRAYSIZE(SMART_NAME_SmartMicronMU03)},
	{L"SmartSanDiskCloud", SMART_NAME_SmartSanDiskCloud, ARRAYSIZE(SMART_NAME_SmartSanDiskCloud)},
	{L"SmartSiliconMotionCVC", SMART_NAME_SmartSiliconMotionCVC, ARRAYSIZE(SMART_NAME_SmartSiliconMotionCVC)},
	{L"SmartAdataIndustrial", SMART_NAME_SmartAdataIndustrial, ARRAYSIZE(SMART_NAME_SmartAdataIndustrial)},
};
