// SPDX-License-Identifier: Unlicense

#pragma once

#define QUOTE_(x) #x
#define QUOTE(x) QUOTE_(x)

#define LIBCDI_MAJOR_VERSION 9
#define LIBCDI_MINOR_VERSION 7
#define LIBCDI_MICRO_VERSION 2
#define LIBCDI_BUILD_VERSION 1

#define LIBCDI_VERSION      LIBCDI_MAJOR_VERSION,LIBCDI_MINOR_VERSION,LIBCDI_MICRO_VERSION,LIBCDI_BUILD_VERSION
#define LIBCDI_VERSION_STR  QUOTE(LIBCDI_MAJOR_VERSION.LIBCDI_MINOR_VERSION.LIBCDI_MICRO_VERSION.LIBCDI_BUILD_VERSION)

#define LIBCDI_COMPANY      "A1ive"
#define LIBCDI_COPYRIGHT    "(C) 2026 A1ive, (C) 2008-2026 hiyohiyo"
#define LIBCDI_FILEDESC     "CrystalDiskInfo DLL"

#define LIBCDI_DLL          "libcdi"
