// SPDX-License-Identifier: Unlicense

#include "gnwinfo.h"

static GNW_LANG GNW_LANG_CHS[] =
{
	{"Loading, please wait ...", "加载中，请稍候 ..."},
	{"File", "文件"},
	{"Refresh", "刷新"},
	{"Exit", "退出"},
	{"Help", "帮助"},
	{"About", "关于"},

	{"Name", "名称"},
	{"Attribute", "属性"},
	{"Data", "数据"},

	{"ACPI Table", "ACPI 表"},
	{"Processor", "处理器"},
	{"Physical Storage", "磁盘"},
	{"Display Devices", "显示设备"},
	{"Network Adapter", "网络适配器"},
	{"PCI Devices", "PCI 设备"},
	{"SMBIOS", "SMBIOS"},
	{"Memory SPD", "内存 SPD"},
	{"Operating System", "操作系统"},
	{"USB Devices", "USB 设备"},

	{"Cache", "缓存"},
	{"Features", "特性"},
	{"SGX", "SGX"},
	{"Multiplier", "倍频"},

	{"OS", "操作系统"},
	{"Computer Name", "计算机名"},
	{"Username", "用户名"},
	{"Min", "最小"},
	{"Max", "最大"},
	{"Current", "当前"},
	{"Status", "状态"},
	{"ID", "ID"},
	{"HWID", "硬件 ID"},
	{"HW Name", "硬件名称"},
	{"Device", "设备"},
	{"Type", "类型"},
	{"Class", "种类"},
	{"Subclass", "子类"},
	{"Signature", "签名"},
	{"Length", "长度"},
	{"Checksum", "校验码"},
	{"Checksum Status", "校验码状态"},
	{"Description", "描述"},
	{"Date", "日期"},
	{"Version", "版本"},
	{"Revision", "修订版"},
	{"Vendor", "供应商"},
	{"Manufacturer", "制造商"},
	{"Serial Number", "序列号"},
	{"Path", "路径"},
	{"Size", "大小"},
	{"Capacity", "容量"},
	{"Drive Letter", "盘符"},
	{"Filesystem", "文件系统"},
	{"Label", "卷标"},
	{"Free Space", "可用空间"},
	{"Total Space", "总空间"},
	{"Partition Table", "分区表"},
	{"Removable", "可移动"},
	{"Table Type", "表类型"},
	{"Table Length", "表长度"},
	{"Table Handle", "表句柄"},
	{"Voltage", "电压"},
	{"Prog IF", "编程接口"},
	{"EDID Version", "EDID 版本"},
	{"Video Input", "视频输入"},
	{"Bits per color", "位/颜色"},
	{"Interface", "界面"},
	{"Resolution", "分辨率"},
	{"Width", "宽度"},
	{"Height", "高度"},
	{"Refresh Rate (Hz)", "刷新率"},
	{"Screen Size", "屏幕尺寸"},
	{"Width (mm)", "宽度 (mm)"},
	{"Height (mm)", "高度 (mm)"},
	{"Diagonal (in)", "对角线 (英寸)"},
	{"Pixel Clock", "像素时钟频率"},
	{"Address", "地址"},
	{"Image", "图像"},
	{"Brand", "品牌"},
	{"Code Name", "代号"},
	{"Family", "系列"},
	{"Model", "型号"},
	{"Stepping", "步进"},
	{"Ext.Family", "扩展系列"},
	{"Ext.Model", "扩展型号"},
	{"Cores", "核心"},
	{"Logical CPUs", "逻辑处理器"},
	{"Total CPUs", "总处理器数"},
	{"CPU Clock (MHz)", "CPU 时钟频率 (MHz)"},
	{"Temperature (C)", "温度 (C)"},
	{"Core Voltage (V)", "核心电压 (V)"},
	{"Bus Clock (MHz)", "总线时钟频率 (MHz)"},
	{"Hypervisor", "虚拟机监控器"},
	{"Start", "起始"},
	{"L1 D", "一级 数据"},
	{"L1 I", "一级 指令"},
	{"L2", "二级"},
	{"L3", "三级"},
	{"Product ID", "产品 ID"},
	{"Product Rev", "产品修订版"},
	{"MAC Address", "MAC 地址"},
	{"DHCP ENabled", "已启用 DHCP"},
	{"Transmit Link Speed", "传输链接速率"},
	{"Receive Link Speed", "接收链接速率"},
	{"Subnet Mask", "子网掩码"},
};
