// SPDX-License-Identifier: Unlicense

#include "gnwinfo.h"

static GNW_LANG GNW_LANG_CHS[] =
{
	{"Loading, please wait ...", "加载中，请稍候 ..."},
	{"File", "文件"},
	{"Refresh", "刷新"},
	{"Export", "导出"},
	{"Exit", "退出"},
	{"Help", "帮助"},
	{"Homepage", "主页"},
	{"About", "关于"},

	{"Name", "名称"},
	{"Attribute", "属性"},
	{"Data", "数据"},

	{"ACPI Table", "ACPI 表"},
	{"Processor", "处理器"},
	{"Physical Storage", "磁盘"},
	{"Display Devices", "显示设备"},
	{"Network Adapter", "网络适配器"},
	{"PCI Devices", "PCI 设备"},
	{"SMBIOS", "SMBIOS"},
	{"Memory SPD", "内存 SPD"},
	{"Operating System", "操作系统"},
	{"USB Devices", "USB 设备"},

	{"Driver", "驱动"},
	{"Driver Path", "驱动路径"},
	{"Language ID", "语言 ID"},
	{"Cache", "缓存"},
	{"Features", "特性"},
	{"SGX", "SGX"},
	{"Multiplier", "倍频"},
	{"String", "字符串"},
	{"OEM String", "OEM 字符串"},
	{"Number of Strings", "字符串数"},
	{"OS", "操作系统"},
	{"Computer Name", "计算机名"},
	{"Username", "用户名"},
	{"Min", "最小"},
	{"Max", "最大"},
	{"Current", "当前"},
	{"Status", "状态"},
	{"ID", "ID"},
	{"HWID", "硬件 ID"},
	{"HW Name", "硬件名称"},
	{"Device", "设备"},
	{"Device Size", "设备大小"},
	{"Device Type", "设备类型"},
	{"Number of Devices", "设备数"},
	{"Type", "类型"},
	{"Class", "种类"},
	{"Subclass", "子类"},
	{"Signature", "签名"},
	{"Length", "长度"},
	{"Checksum", "校验码"},
	{"Checksum Status", "校验码状态"},
	{"Description", "描述"},
	{"Date", "日期"},
	{"Release Date", "发布日期"},
	{"Version", "版本"},
	{"Revision", "修订版"},
	{"Vendor", "供应商"},
	{"Manufacturer", "制造商"},
	{"Serial Number", "序列号"},
	{"Path", "路径"},
	{"Size", "大小"},
	{"Location", "位置"},
	{"Function", "功能"},
	{"Capacity", "容量"},
	{"Max Capacity", "最大容量"},
	{"Number of Slots", "插槽数"},
	{"Error Correction", "错误校正"},
	{"Drive Letter", "盘符"},
	{"Filesystem", "文件系统"},
	{"Label", "卷标"},
	{"Free Space", "可用空间"},
	{"Total Space", "总空间"},
	{"Partition Table", "分区表"},
	{"MBR Signature", "MBR 签名"},
	{"Removable", "可移动"},
	{"Table Type", "表类型"},
	{"Table Length", "表长度"},
	{"Table Handle", "表句柄"},
	{"Voltage", "电压"},
	{"Prog IF", "编程接口"},
	{"EDID Version", "EDID 版本"},
	{"Video Input", "视频输入"},
	{"Bits per color", "位/颜色"},
	{"Interface", "界面"},
	{"Resolution", "分辨率"},
	{"Width", "宽度"},
	{"Height", "高度"},
	{"Refresh Rate (Hz)", "刷新率"},
	{"Screen Size", "屏幕尺寸"},
	{"Width (mm)", "宽度 (mm)"},
	{"Height (mm)", "高度 (mm)"},
	{"Diagonal (in)", "对角线 (英寸)"},
	{"Pixel Clock", "像素时钟频率"},
	{"Address", "地址"},
	{"Image", "图像"},
	{"Brand", "品牌"},
	{"Code Name", "代号"},
	{"Family", "系列"},
	{"Model", "型号"},
	{"Stepping", "步进"},
	{"Ext.Family", "扩展系列"},
	{"Ext.Model", "扩展型号"},
	{"Cores", "核心"},
	{"Logical CPUs", "逻辑处理器"},
	{"Total CPUs", "总处理器数"},
	{"CPU Clock (MHz)", "CPU 时钟频率 (MHz)"},
	{"Temperature (C)", "温度 (C)"},
	{"Core Voltage (V)", "核心电压 (V)"},
	{"Bus Clock (MHz)", "总线时钟频率 (MHz)"},
	{"Hypervisor", "虚拟机监控器"},
	{"Start", "起始"},
	{"L1 D", "一级 数据"},
	{"L1 I", "一级 指令"},
	{"L2", "二级"},
	{"L3", "三级"},
	{"Product Name", "产品名称"},
	{"Product ID", "产品 ID"},
	{"Product Rev", "产品修订版"},
	{"MAC Address", "MAC 地址"},
	{"DHCP Enabled", "已启用 DHCP"},
	{"DHCP Server", "DHCP 服务器"},
	{"Transmit Link Speed", "传输链接速率"},
	{"Receive Link Speed", "接收链接速率"},
	{"Subnet Mask", "子网掩码"},
	{"Unicast Address", "单播地址"},
	{"Multicast Address", "多播地址"},
	{"Anycast Address", "任播地址"},
	{"DNS Server", "DNS 服务器"},
	{"Gateway", "网关"},
	{"Received (Octets)", "已接收 (八比特组)"},
	{"Sent (Octets)", "已发送 (八比特组)"},
	{"MTU (Byte)", "最大传输单元 (字节)"},
	{"Port Type", "端口类型"},
	{"Speed (MT/s)", "速度 (MT/s)"},
	{"Speed (MHz)", "速度 (MHz)"},
	{"Memory Type", "内存类型"},
	{"Module Type", "模组类型"},
	{"DNS Domain", "DNS 域"},
	{"DNS Hostname", "DNS 主机名"},
	{"System Directory", "系统目录"},
	{"Windows Directory", "Windows 目录"},
	{"Uptime", "正常运行时间"},
	{"Processor Architecture", "处理器架构"},
	{"Page Size", "页大小"},
	{"Firmware", "固件"},
	{"Secure Boot", "安全启动"},
	{"Power Status", "电源状态"},
	{"Memory Usage", "内存使用"},
	{"Physical Memory", "物理内存"},
	{"Paging File", "页面文件"},
	{"Free", "可用"},
	{"Total", "总计"},
};
